name: Chart Validator
on: push
jobs:
  chart-lint:
    runs-on: ubuntu-latest
    outputs:
      charts: ${{ steps.filter.outputs.charts }}
    steps:
    - uses: actions/checkout@v2
    - uses:  dorny/paths-filter@v2
      id: filter
      with:
        list-files: shell
        filters: |
          charts:
            - added|modified: 'charts/*/templates/*'
    - run: echo ${{ steps.filter.outputs.charts }}
    - uses: actions/setup-python@v2
    - uses: jannekem/run-python-script-action@v1
      id: python
      with:
        script: |
            string='${{ steps.filter.outputs.charts_files }}'
            location=string.split("templates",1)[0]
            print(location)
            set_output("chart_path",location)
    - run: echo ${{ steps.python.outputs.chart_path }}
    - name: Print errors
      if: steps.script.outputs.error == 'true'
      run: |
        printenv "SCRIPT_STDOUT"
        printenv "SCRIPT_STDERR"
    - name: values-file
      id: values
      run: echo ./${{ steps.python.outputs.chart_path }}templates/values.yaml
    - name: helm-check
      uses: gunish-dt/helm-check-action@0.1.4
      env:
        CHART_LOCATION: ./${{ steps.python.outputs.chart_path }}
        CHART_VALUES: ./${{ steps.values.outputs.values_files }}

    